### ISSUE TITLE
step for large polygons leads to gaps in the area coverage

### ISSUE THREAD

**Issue by mkdsfm** [Postlagerkarte/geohash-dotnet#51]
https://github.com/Postlagerkarte/geohash-dotnet/blob/635ef8625f5f4c23af6b304ba6373ff76db29671/src/PolygonHasher.cs#L53-L54

this step for large polygons leads to gaps in the coverage of the area with geohashes:

![image](https://github.com/Postlagerkarte/geohash-dotnet/assets/56064826/be30a58c-4fe5-4acc-a4b1-f704229bbb53)

I suggest replacing it with the length and width of the geohash box:
```cs
double latStep = 180 / Math.Pow(2, (5*geohashPrecision-geohashPrecision%2)/2);
double lngStep = 180 / Math.Pow(2, (5*geohashPrecision+geohashPrecision%2)/2-1);
```

**Comment by Postlagerkarte** [comment]
Thank you for reporting. This should be fixed now.
